# Site settings
title: fatemeh amiri | فاطمه امیری
email: famiri145@yahoo.com
description: توسعه‌دهنده رابط کاربری
baseurl: "http://f-amiri.ir/"
url: "http://f-amiri.ir"
twitter: _Karamii
github:  fatemeh94
behance: HosseinKarami
# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
paginate_path: "blog/page:num/"
exclude: ["node_modules", "gulpfile.js", "package.json"]